import {Home} from 'components/Home/Home'
import type { NextPage } from 'next'
import Head from 'next/head'
import styles from 'styles/Index.module.scss';


const Index: NextPage = () => {

  return (
    <div className={styles.Index}>
		<div>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main>
				<Home />
			</main>

			<footer>
				Powered by{' Lars'}
			</footer>
		</div>
    </div>
  )
}

export default Index;
